### PR TITLE
Show images under https only

### PR DESCRIPTION
**Pull request by tattn**
Hi!

This is a cool plugin! :sunglasses:

I want to display LGTM images under https.
So, I wanna retry fetching an image if the url of the fetching image is not https.

How do you think about this change?

### CODE REVIEW

**Comment by tattn** [comment]
CI (Ruby 2.1.3) is broken?? 🤔

**Comment by leonhartX** [comment]
There seems more http images than https, so I think get https image only is too much as a default behavior, make it as an option should be better.
BTW, the CI broken in ruby 2.1.3 looks like something about danger-plugin-api gem went wrong so don't need to care about.

**Comment by tattn** [comment]
@leonhartX
Oh, I totally agree with what you are saying :)
If so, how do you think about adding the following option?

```ruby
def check_lgtm(image_url: nil, https_image_only: false)
```

If you are reluctant about this, I use my fork version and close this PR 👍

**Comment by leonhartX** [comment]
@tattn Yes, that option looks great!

**Comment by tattn** [comment]
@leonhartX  I added the option 👍

**Review by leonhartX — COMMENTED** [review]
Can you add spec of the new option?

**Comment by tattn** [comment]
OK. I added the spec.
Does it make sense?

**Comment by leonhartX** [comment]
Thanks!

**Comment by tattn** [comment]
Thank you for your support 😄

**Comment by leonhartX** [comment]
v1.0.0 released with this option.

**Pull request merged**
